# These are supported funding model platforms

patreon: streetsidesoftware
tidelift: 'npm/cspell'
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
  - streetsidesoftware
open_collective: cspell
# ko_fi: # Replace with a single Ko-fi username
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
custom:
  # - "https://www.paypal.com/donate/?hosted_button_id=26LNBP2Q6MKCY"
  # - streetsidesoftware.com/support "title"
