name: Labels

on:
  pull_request:
    types: [opened, reopened, labeled, edited, synchronize, unlabeled, closed]

jobs:
  fix-labels-on-pr:
    name: Fix labels on PR
    if: ${{ contains(github.event.pull_request.labels.*.name, 'fix') && contains(github.event.pull_request.labels.*.name, 'Update Dictionaries')  }}
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - name: Remove label 'fix'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.number }} --remove-label fix
